version: '3.8'
services:
  tts-app:
    build:
      context: ./docker
      dockerfile: Dockerfile.app
    restart: unless-stopped
    # Expose internal port for nginx to talk to
    ports:
      - "8000:8000"

  nginx-proxy:
    image: nginx:stable
    depends_on:
      - tts-app
    ports:
      - "5002:5002"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
