name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          if npm run -s lint; then echo "lint passed"; else echo "lint failed"; exit 1; fi

      - name: Run tests
        run: npx vitest --run

      - name: Build
        run: npm run build

      - name: Validate assets referenced in dist/manifest.json exist in dist/
        # After build, parse the built manifest (dist/manifest.json) and ensure any referenced icons
        # and web_accessible_resources are present in the build output (dist/).
        run: |
          set -euo pipefail

          # Extract referenced assets (icons + web_accessible_resources) from the built manifest
          node -e "const fs=require('fs');const m=JSON.parse(fs.readFileSync('dist/manifest.json','utf8'));const icons=Object.values(m.icons||{});let war=[];if(m.web_accessible_resources){ if(Array.isArray(m.web_accessible_resources)){ m.web_accessible_resources.forEach(e=>{ if(typeof e==='string') war.push(e); else if(Array.isArray(e.resources)) war.push(...e.resources); else if(e.resources) war.push(...e.resources); }); } } const unique=[...new Set([...icons,...war])]; console.log(unique.join('\n'))" > /tmp/manifest-assets.txt || (echo 'Failed to read dist/manifest.json' && exit 1)

          missing=0
          while IFS= read -r asset; do
            # skip empty lines
            [ -z "${asset}" ] && continue
            # Normalize path (dist relative)
            path="dist/${asset}"
            if [[ "${asset}" == *"*"* ]]; then
              # asset contains a glob; check if any match
              if compgen -G "${path}" >/dev/null; then
                echo "Found matches for glob: ${asset}"
              else
                echo "::error file=dist/manifest.json::No files match glob ${asset} in dist/" >&2
                missing=1
              fi
            else
              if [ -f "${path}" ]; then
                echo "Found ${path}"
              else
                echo "::error file=dist/manifest.json::Referenced asset ${asset} missing from dist/" >&2
                missing=1
              fi
            fi
          done < /tmp/manifest-assets.txt

          if [ "$missing" -eq 1 ]; then
            echo "One or more assets referenced in dist/manifest.json are missing from dist/." >&2
            exit 1
          fi
